### ISSUE TITLE
失效了吗？

### ISSUE THREAD

**Issue by yxjxx** [zeruniverse/QQParking#12]
2015/11/08

**Comment by zeruniverse** [comment]
此链接自动检测登陆拉取，目前为PASS： https://travis-ci.org/zeruniverse/QQParking

如果您无法使用请提交具体错误

**Comment by yxjxx** [comment]
感谢回复。

为了节省打字的时间，我就简单的录个视频说明一下情况吧。😊

https://monosnap.com/file/Xe1Py0Q3I5l4LGDd7QADggeK2ZBipf

原来使用自己申请的 API KEY 和邮箱一直可以正常使用，直到最近无法正常登陆。换成你提供的测试用帐号问题依旧。

log 报错信息

```
Tue, 10 Nov 2015 10:36:25  QQBot.py[line:479] CRITICAL 正在获取登陆页面
Tue, 10 Nov 2015 10:36:27  QQBot.py[line:483] CRITICAL 正在获取appid
Tue, 10 Nov 2015 10:36:27  QQBot.py[line:101] ERROR Get AppId Error
Tue, 10 Nov 2015 10:36:27  QQBot.py[line:801] ERROR Get AppId Error
```

非常乐意提供你可能需要的进一步的信息。

**Comment by zeruniverse** [comment]
已重现该错误，感谢！将在有时间的时候解决。

疑似返回的格式变更，如果您能修复该问题，请提交PR.

顺便 @juxingzhutou ：是同样的问题吗？

**Comment by juxingzhutou** [comment]
我认为应该同样是html内容格式变化的问题，稍后我提交一个PR

**Comment by juxingzhutou** [comment]
@zeruniverse 已提交PR，修复了登录的问题

**Comment by zeruniverse** [comment]
Fixed

**Comment by yxjxx** [comment]
经测试原来通过「QQ安全中心」扫码登陆的方式已经被官方改为 「手机QQ」扫码登陆了。

可以改下 README 。😊

**Comment by juxingzhutou** [comment]
@yxjxx QQ安全中心扫码登录还是可以用的啊

**Comment by yxjxx** [comment]
@juxingzhutou 可是我这边用不了了啊，iOS 最新版。🤔️

**Comment by yxjxx** [comment]
@zeruniverse 而且现在网页上也提示使用手机QQ扫码了。

![image](https://cloud.githubusercontent.com/assets/2312081/11056266/f7333986-87ba-11e5-8251-e9902e821f58.png)

**Comment by zeruniverse** [comment]
新问题请开新issue讨论

谢谢！
