### ISSUE TITLE
登录时显示错误"Line550 CRITICAL 登录失败，正在重试"

### ISSUE THREAD

**Issue by jwhsir** [zeruniverse/QQParking#14]
登录时显示错误"Line550 CRITICAL 登录失败，正在重试"

tulingkey = '4f1a31632af66578e1c8d22*********_'
mailserver = 'smtp.163.com'
mailsig = 'QQParking Notification'
mailuser = 'jiang**_**@163.com'
mailpass = '******_'
sendtomail = 'jiang**_**@163.com'

在QQBot.py中的设定如上，应该没有问题。已经成功扫描V.png，并在手机上显示“已经在电脑登录”。

**Comment by zeruniverse** [comment]
Related to issue #15

**Comment by zeruniverse** [comment]
目前比较忙，如果LZ能自行解决的话能不能给个PR？第一眼看是协议的问题。QQ换协议就是频繁

**Comment by jwhsir** [comment]
我又尝试了几次，仍不能成功。自己实在是没有能力解决啊。在服务器搭建这个只是为了尝鲜，您要是忙碌就有空再来debug好了。    ps...“给个PR”是指什么...？

**Comment by zeruniverse** [comment]
已解决

**Comment by jwhsir** [comment]
我还是没有办法成功...我已经下载了新的代码并上传至服务器 使用过程严格按照您的教程...还是提示一样的错误 但是我的手机上明明已经显示已经在电脑上登陆了呀

**Comment by zeruniverse** [comment]
请贴一下完整的LOG

另外 您可能需要先登录一下网页版的QQ 再运行程序。

**Comment by zeruniverse** [comment]
我确实是能用的，你或者可以试试我的 http://qqbot.jeffery.cc

**Comment by jwhsir** [comment]
Wed, 03 Feb 2016 04:03:32  qqbot.py[line:827] ERROR cannot concatenate 'str' and 'int' objects
用了您的网页服务的确成功登陆了...我也不知道为什么...这是我用了您的网页的服务的错误提示。

**Comment by zeruniverse** [comment]
我确实可以正常登陆+发消息 不管是网页版的还是python版的……你能加几个debug语句看看是哪个返回值有问题么……
