### ISSUE TITLE
请问Android QQ协议分析出了吗？好期待啊

### ISSUE THREAD

**Issue by zjcnew** [zeruniverse/QQParking#18]
Android QQ协议分析出来了吗，现在我用smartqq协议做生产环境的监控告警消息收发，太tM恶心了真受不了。迫切希望尽快出个稳定的安卓QQ、PC QQ协议在Linux平台跑！

**Comment by zeruniverse** [comment]
https://github.com/zeruniverse/QQRobot/issues/28

你可以跟上面网址issue的人讨论下。我没啥时间搞这个
