### ISSUE TITLE
INFO Login success Thu, 04 Jan 2018 22:57:56  QQBot.py[line:545] CRITICAL 登陆二维码用时0.586秒 Thu, 04 Jan 2018 22:58:02  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103} Thu, 04 Jan 2018 22:58:03  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103} Thu, 04 Jan 2018 22:58:05  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103} Thu, 04 Jan 2018 22:58:06  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103} Thu, 04 Jan 2018 22:58:07  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103} Thu, 04 Jan 2018 22:58:08  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103} Thu, 04 Jan 2018 22:58:08  QQBot.py[line:639] CRITICAL 轮询错误超过五次

### ISSUE THREAD

**Issue by peaceanddemocracy** [zeruniverse/QQParking#19]
INFO Login success
Thu, 04 Jan 2018 22:57:56  QQBot.py[line:545] CRITICAL 登陆二维码用时0.586秒
Thu, 04 Jan 2018 22:58:02  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103}
Thu, 04 Jan 2018 22:58:03  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103}
Thu, 04 Jan 2018 22:58:05  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103}
Thu, 04 Jan 2018 22:58:06  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103}
Thu, 04 Jan 2018 22:58:07  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103}
Thu, 04 Jan 2018 22:58:08  QQBot.py[line:647] INFO Check html: {"errmsg":"error","retcode":103}
Thu, 04 Jan 2018 22:58:08  QQBot.py[line:639] CRITICAL 轮询错误超过五次

**Comment by zeruniverse** [comment]
https://github.com/zeruniverse/QQRobot/issues/31
