### ISSUE TITLE
另外能不能说一下这些字段的意思

### ISSUE THREAD

**Issue by peaceanddemocracy** [zeruniverse/QQParking#20]
VFWebQQ = ''
AdminQQ = '0'

#My QQ
MyUIN = 0
QQUserName = ''
#Put UserNameList Here to avoid multiple requests
MarkNameList = []
NickNameList = []
GroupList = []
DiscussionList = []

需要设置嘛？

**Comment by zeruniverse** [comment]
不需要 只需要按readme设置.txt

**Comment by peaceanddemocracy** [comment]
self.tuin = tuin
        self.isSess = isSess
        self.group_sig=group_sig
        self.service_type=service_type
        self.lastcheck = time.time()
        self.lastseq=0
        self.lastmail=0
        self.isrecord=0
        self.ini_txt=ini_txt
        self.ini_msgid=ini_msgid
        self.sess_group_id = myid
        self.replystreak = 0

这些为0的要改为1开启么？

**Comment by peaceanddemocracy** [comment]
record=0时貌似无法记录到邮件

**Comment by zeruniverse** [comment]
这些是变量初始化，都不需要设置，record=0是对的，表示用户当前还没有输入record命令。

**Comment by peaceanddemocracy** [comment]
好的谢谢
