### ISSUE TITLE
登陆一段时间后会自动下线

### ISSUE THREAD

**Issue by peaceanddemocracy** [zeruniverse/QQParking#21]
登陆成功几小时后会因为103错误自动下线，有办法解决么？

**Comment by zeruniverse** [comment]
你用smartqq多登多发也会103 没办法

**Comment by peaceanddemocracy** [comment]
这个是协议上的缺陷么？另外发现多次发送消息后系统会发送失败，但是我QQ客户端聊天还是正常的

**Comment by zeruniverse** [comment]
对，smartqq确实比较容易被认为是外挂而下线。这个是TX的问题没有办法。你用浏览器时间长了也会被弹下线的。一般1天左右。
