### ISSUE TITLE
登录成功报错ERROR cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by peaceanddemocracy** [zeruniverse/QQParking#22]
ERROR cannot concatenate 'str' and 'int' objects

**Comment by zeruniverse** [comment]
错误在第几行？

**Comment by peaceanddemocracy** [comment]
没有提示，是在log中看到的，但是有时运行就没问题，不知道是什么原因导致

**Comment by zeruniverse** [comment]
那不用去管它 应该是报错导致的 看别的错误就好

**Comment by peaceanddemocracy** [comment]
line:790

**Comment by peaceanddemocracy** [comment]
QQBot.py[line:790] ERROR cannot concatenate 'str' and 'int' objects

**Comment by peaceanddemocracy** [comment]
这个问题一会有一会又正常

**Comment by peaceanddemocracy** [comment]
if len(sys.argv) > 1:
        vpath = sys.argv[1]
    if len(sys.argv) > 2:
        qq = sys.argv[2]

    try:
        pass_time()
        qqLogin = Login(vpath, qq)
    except Exception, e:
        logging.error(str(e))
        os._exit(1)
    try:
        t_check = check_msg()
        t_check.setDaemon(True)
        t_check.start()
        t_check.join()

这是line781到796的

报错的line790是这行：logging.error(str(e))

**Comment by peaceanddemocracy** [comment]
另外貌似最近登录成功后收不到私聊消息，只能间接性收到群消息

**Comment by zeruniverse** [comment]
这个正常的，用浏览器多登陆几次让TX觉得你有用smartqq的习惯就好了

**Comment by zeruniverse** [comment]
这个错误说明登陆失败了。smartqq不稳定，没办法
